name: Release Build Confirmation

on:
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

  
jobs:
  check_semver:
    name: Check semver
    runs-on: ubuntu-latest
    steps:
      - uses: obi1kenobi/cargo-semver-checks-action@v2
  